services:
  - type: web
    name: ServPro
    env: docker
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 5000
